/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TUAN5_NguyenThanhSieu;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author Administrator
 */
public class frmAlice extends javax.swing.JFrame {

    /**
     * Creates new form frmAlice
     */
    public frmAlice() {
        initComponents();
    }

    
    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkhoaa = new javax.swing.JTextField();
        txtkhoab = new javax.swing.JTextField();
        txtkhoachung = new javax.swing.JTextField();
        txtmahoakab = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnKhoaA = new javax.swing.JButton();
        btnkhoab = new javax.swing.JButton();
        btnkhoachung = new javax.swing.JButton();
        btnmahoakb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alice");

        jLabel2.setText("Khoá Alice:");

        jLabel3.setText("Khoá Bob:");

        jLabel4.setText("Khoá KAB:");

        jLabel5.setText("Mã Hoá KAB:");

        txtkhoaa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtkhoab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtkhoachung.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtmahoakab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jButton1.setText("Mã hoá / Giải mã");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnKhoaA.setText("Tạo Khoá A");
        btnKhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaAActionPerformed(evt);
            }
        });

        btnkhoab.setText("Hiển Thị KB");
        btnkhoab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoabActionPerformed(evt);
            }
        });

        btnkhoachung.setText("Khoá Chung");
        btnkhoachung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoachungActionPerformed(evt);
            }
        });

        btnmahoakb.setText("Mã Hoá KAB");
        btnmahoakb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoakbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtkhoachung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(txtkhoab, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkhoaa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmahoakab))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKhoaA)
                                    .addComponent(btnkhoab)
                                    .addComponent(btnkhoachung)
                                    .addComponent(btnmahoakb))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkhoaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkhoab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkhoachung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhoachung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmahoakb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaAActionPerformed
        // TODO add your handling code here:
        try{
            AlgorithmParameterGenerator paramGen = AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            
            DHParameterSpec dhSkipParamSpec = (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            
            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair();
            
            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());
            
            byte[] alicePubKeyEnc = aliceKpair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("M:\\A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();
            txtkhoaa.setText(alicePubKeyEnc.toString());
            
        }catch(Exception ex){}
    }//GEN-LAST:event_btnKhoaAActionPerformed

    private void btnkhoabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoabActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis = new FileInputStream("M:\\B.pub");
            byte[] bkeyP = new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            txtkhoab.setText(bkeyP.toString());
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoabActionPerformed

    private void btnkhoachungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoachungActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis = new FileInputStream("M:\\B.pub");
            byte[] bobPubKeyEnc = new byte[fis.available()];
            fis.read(bobPubKeyEnc);
            fis.close();
            
            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(bobPubKeyEnc);
            bobPubKey = aliceKeyFac.generatePublic(x509KeySpec);
            System.out.println("Executing PHASE1 of key agreement...");
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] aliceShareSecret = aliceKeyAgree.generateSecret();
            
            System.out.println("Khoa chung: secret (DEBUG ONLY): " + CryptoUtil.toHexString(aliceShareSecret));
            txtkhoachung.setText(CryptoUtil.toHexString(aliceShareSecret));
        }catch(Exception ex){}
    }//GEN-LAST:event_btnkhoachungActionPerformed

    private void btnmahoakbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoakbActionPerformed
        // TODO add your handling code here:
        try{
            aliceKeyAgree.doPhase(bobPubKey, true);
            aliceDesKey = aliceKeyAgree.generateSecret("DES");
            
            txtmahoakab.setText(aliceDesKey.toString());
            BufferedWriter bw = null;
            String fileName = "M:\\KhoaA.txt";
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(aliceDesKey.toString());
            bw.close();
        }catch(Exception ex){}
    }//GEN-LAST:event_btnmahoakbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmDESCS des = new frmDESCS();
        des.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoaA;
    private javax.swing.JButton btnkhoab;
    private javax.swing.JButton btnkhoachung;
    private javax.swing.JButton btnmahoakb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtkhoaa;
    private javax.swing.JTextField txtkhoab;
    private javax.swing.JTextField txtkhoachung;
    private javax.swing.JTextField txtmahoakab;
    // End of variables declaration//GEN-END:variables
}
